## LHS_design
# 
#========================================================	
# ---
### title: Design LHS sampling
# author: Marie Gilbertson
# date: "07/23/2020"
#---
# ##  Preamble	
# 
# What this code does:
# 1. Generates latin hypercube sampling routine for FIV-->FeLV simulations

##### Clear Environment #####
remove(list=ls())

##### Set seed #####
set.seed(4575)


#### load libraries ####
library(lhs)
library(extraDistr) # for uniform discrete distribution

# Parameter distributions divided into N equal probability intervals (N = sample size)
# Marino et al 2009: "The choice for N should be at least k+1, where k is the number of paramters varied,
# but usually much larger to ensure accuracy."


# parameters to vary (k)
# 1. probability of transmission 
# 2. duration of infection (for progressive infections)
# 3. modifier for duration of infection for regressive infections
# 4. modifier for probability of transmission from regressive individuals
# 5. population size
# 6. contact rate
# 7. proportion adults
# 8. re-spawn rate
# 9. network density
# 10. vaccination rate
# 11. vaccine efficacy



# LHS tutorial: https://cran.r-project.org/web/packages/lhs/vignettes/lhs_basics.html
# basic design with 150 samples from 11 parameters
A <- randomLHS(150, 11)

# now transform the margins of the design (the columns) into other distributions 

B <- matrix(nrow = nrow(A), ncol = ncol(A))

# 1. probability of transmission (beta-ish)
# range: 9/52 - 15/52, uniform continuous distribution
B[,1] <- qunif(A[,1], min = 9/52, max = 15/52)

# 2. duration of infection (for progressive infections)
# two different durations (short, long)
# uniform discrete distribution to draw from these two distributions (1 = short, 2 = long)
B[,2] <- qdunif(A[,2], min = 1, max = 2)

# 3. modifier for duration of infection for regressive infections
# two different modifiers (0.5 and 1)
# uniform discrete distribution to draw from these two modifiers (1 = 0.5 (shorter), 2 = 1 (same))
B[,3] <- qdunif(A[,3], min = 1, max = 2)

# 4. modifier for probability of transmission from regressive individuals
# four different modifiers (0, 0.1, 0.5, 1)
# uniform discrete distribution to draw from these four modifiers (1 = 0, 2 = 0.1, 3 = 0.5, 4 = 1)
B[,4] <- qdunif(A[,4], min = 1, max = 4)


# 5. population size
# range: 80 - 120, uniform discrete distribution (can't have half a panther)
# 80 from Roy McBride minimum count; 120 from McClintock et al
B[,5] <- qdunif(A[,5], min = 80, max = 120)

# 6. contact rate
# range: 0.1 - 0.4, uniforrm continuous
B[,6] <- qunif(A[,6], min = 0.1, max = 0.4)

# 7. proportion adults
# rather than having two separate LHS parameters, examine range of values generated by
# two sets of normal distributions based on data from Desert Puma (Logan and Sweanor)
adults <- rnorm(1000, mean = 0.61, sd = 0.09)
juves <- rnorm(1000, mean = 0.06, sd = 0.02)
props <- adults/(juves+adults)
mean.prop <- mean(props)
sd.prop <- sd(props)
# Now LHS will be transformed to normal distribution, with mean = mean.prop and sd = sd.prop
B[,7] <- qnorm(A[,7], mean = mean.prop, sd = sd.prop)
# some may be just over 1 (can't have a proportion over one), so adjust these to be just under 1
which(B[,7]>=1)
max(subset(B[,7], B[,7]<1))
B[,7][B[,7]>=1] <- 0.99
any(B[,7]>=1)
hist(B[,7])

# 8. re-spawn rate
# range: 1/12 - 1/4; uniform continuous distribution
B[,8] <- qunif(A[,8], min = 1/12, max = 1/4)

# 9. network density
# range: 0.05 - 0.15; uniform continuous distribution
B[,9] <- qunif(A[,9], min = 0.05, max = 0.15)

# 10. vaccination rate
# range: 1/2 - 1/1, uniform continuous distribution
B[,10] <- qunif(A[,10], min = 1/2, max = 1)

# 11. vaccine efficacy
# range: 0.4-1, uniform continuous distribution
B[,11] <- qunif(A[,11], min = 0.4, max = 1)



# evaluate correlation matrix scatterplots
pairs(A)
pairs(B)


# name columns by parameter
colnames(B) <- c("beta",
                 "progr.dur",
                 "regr.dur.c",
                 "c.beta",
                 "pop.size",
                 "c.rate",
                 "a_prop",
                 "terr.repop",
                 "net.den",
                 "vax.rate",
                 "vax.eff"
                 )


# convert to dataframe
B.frame <- data.frame(B)


# duplicate to add "proportion per infection outcome" parameter
C.frame <- B.frame
C.frame$prop.outcomes <- 1
# 1 = 25/25/50

B.frame <- C.frame


# add parameter set id #
B.frame$set.id <- seq(1:nrow(B.frame))
B.frame <- B.frame[,c(13,1:12)] # reorder columns 


# Save parameter sets
# save(B.frame, file = "LHS parameter sets.Rdata")
